# Generated by Django 5.2.13 on 2026-05-03 05:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PainPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('test_failure', 'Test Failure'), ('slow_execution', 'Slow Execution'), ('low_coverage', 'Low Coverage'), ('flaky_test', 'Flaky Test')], max_length=50)),
                ('description', models.TextField()),
                ('file_path', models.CharField(max_length=500)),
                ('occurrence_count', models.IntegerField(default=1)),
                ('first_seen', models.DateTimeField(auto_now_add=True)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('resolved', models.BooleanField(default=False)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pain_points', to='github_integration.githubrepo')),
            ],
            options={
                'ordering': ['-occurrence_count', '-last_seen'],
            },
        ),
        migrations.CreateModel(
            name='TestOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execution_time', models.FloatField(help_text='Test execution time in seconds')),
                ('passed', models.BooleanField(default=False)),
                ('failed_count', models.IntegerField(default=0)),
                ('error_message', models.TextField(blank=True)),
                ('coverage_percentage', models.FloatField(default=0.0)),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('test_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='outcomes', to='ai_engine.testfile')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DevInsight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('tests_generated', models.IntegerField(default=0)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_failed', models.IntegerField(default=0)),
                ('avg_execution_time', models.FloatField(default=0.0)),
                ('code_coverage', models.FloatField(default=0.0)),
                ('files_analyzed', models.IntegerField(default=0)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='insights', to='github_integration.githubrepo')),
            ],
            options={
                'ordering': ['-date'],
                'unique_together': {('repo', 'date')},
            },
        ),
    ]
