# Generated by Django 5.2.13 on 2026-05-03 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_engine', '0001_initial'),
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PipelineRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commit_hash', models.CharField(max_length=100)),
                ('commit_message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('running', 'Running'), ('passed', 'Passed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('triggered_by', models.CharField(blank=True, max_length=100)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_integration.githubrepo')),
            ],
        ),
        migrations.CreateModel(
            name='BuildResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('output_log', models.TextField(blank=True)),
                ('error_log', models.TextField(blank=True)),
                ('duration_seconds', models.FloatField(default=0.0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('test_file', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='ai_engine.testfile')),
                ('pipeline_run', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='ci_pipeline.pipelinerun')),
            ],
        ),
        migrations.CreateModel(
            name='QualityGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_coverage', models.FloatField(default=0.0)),
                ('tests_passed', models.IntegerField(default=0)),
                ('tests_failed', models.IntegerField(default=0)),
                ('coverage_threshold', models.FloatField(default=80.0)),
                ('passed', models.BooleanField(default=False)),
                ('evaluated_at', models.DateTimeField(auto_now_add=True)),
                ('pipeline_run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='ci_pipeline.pipelinerun')),
            ],
        ),
    ]
