# Generated by Django 5.2.13 on 2026-05-03 01:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CodeFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.CharField(max_length=500)),
                ('file_content', models.TextField()),
                ('language', models.CharField(default='python', max_length=50)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('repo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='github_integration.githubrepo')),
            ],
            options={
                'unique_together': {('repo', 'file_path')},
            },
        ),
        migrations.CreateModel(
            name='ChangeEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_content', models.TextField()),
                ('new_content', models.TextField()),
                ('commit_hash', models.CharField(blank=True, max_length=100)),
                ('commit_message', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('detected_at', models.DateTimeField(auto_now_add=True)),
                ('processed_at', models.DateTimeField(blank=True, null=True)),
                ('code_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='change_events', to='ai_engine.codefile')),
            ],
        ),
        migrations.CreateModel(
            name='TestFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_content', models.TextField()),
                ('generated_by_ai', models.BooleanField(default=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('is_passing', models.BooleanField(default=False)),
                ('code_file', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='test_file', to='ai_engine.codefile')),
            ],
        ),
    ]
