# Generated by Django 5.2.13 on 2026-05-03 11:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='github_token',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='githubrepo',
            name='repo_url',
            field=models.URLField(blank=True),
        ),
    ]
