# Generated by Django 5.2.13 on 2026-05-03 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('github_integration', '0002_githubrepo_is_active_alter_githubrepo_github_token_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='githubrepo',
            name='last_scanned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='githubrepo',
            name='scan_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('scanning', 'Scanning'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
